#!/bin/bash

## Description: Drupal Canvas: Install Drupal site.
## Aliases: si
## Usage: site-install
## Example: "ddev site-install"
## ExecRaw: true

set -e

# Install Drupal.
drush site-install \
    --account-pass=admin \
    --site-name="Canvas: DrupalCon Vienna 2025" \
    --account-pass=admin \
    --yes

# Enable modules.
drush pm:enable --yes canvas canvas_dev_mode config default_content

# Apply recipes.
drush recipe ../recipes/canvas_dev_humanify
drush recipe ../recipes/canvas_dev_stark
drush recipe ../recipes/canvas_dev_oauth

# Generate OAuth keys.
drush simple-oauth:generate-keys /var/www/html/web/sites/default/files
# Resave the consumer entity (OAuth client) to update the secret, which gets
# encrypted using the generated keys.
drush php-eval "
    \$consumer = \Drupal::service('entity_type.manager')->getStorage('consumer')->loadByProperties(['client_id' => 'cli']);
    \$entity = reset(\$consumer);
    \$entity->set('secret', 'secret');
    \$entity->save();
"
